Numpy an acronym for Numerical Python, is a package to perform scientific computing in python efficiently.
It includes Random number generation , functions for basic linear algebra, fourier transforms as well as .

In [1]:
import numpy as np

# Numpy Arrays



In [2]:
# Calculating PCR through Numpy arrays

In [3]:
put_vol = [52.89, 45.14, 63.84, 77.1,74.6]

In [4]:
call_vol = [49.51,50.45, 59.11,80.49,65.11] # volume in lacs

In [5]:
n_put_vol = np.array(put_vol)

In [6]:
n_call_vol = np.array(call_vol)

In [7]:
pcr = n_put_vol/n_call_vol

In [8]:
pcr

array([1.06826904, 0.89474727, 1.0800203 , 0.95788297, 1.14575334])

In [9]:
# Creating lists

In [10]:
list1 = [1,2,3]

In [11]:
list2 = [5,6,4]

In [12]:
# adding two lists
# adding list together only paster two columns and generate a list with 6 elements.

In [13]:
list1 + list2

[1, 2, 3, 5, 6, 4]

In [14]:
# Creating Arrays

In [15]:
arr1 = np.array([1,2,3])

In [16]:
arr2 = np.array([5,6,4])

In [17]:
arr1+ arr2  # in array if we do + it will add sum element wise in arrays

array([6, 8, 7])

In [18]:
arr3 = np.array([1,2,4,6])

In [20]:
arr2 + arr3 # as u can see if element size is not equal it will through error

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [21]:
# checking array type

In [23]:
type(arr1)  # ndarray stands for N-Dimensional Array

numpy.ndarray

In [24]:
# Creating 2 Dimensional array

In [25]:
n_2d = np.array([put_vol , call_vol])

In [26]:
n_2d

# n2d is rectagunlar data structure. 

array([[52.89, 45.14, 63.84, 77.1 , 74.6 ],
       [49.51, 50.45, 59.11, 80.49, 65.11]])

# Array creation using Built In function

# Zeros(shape, dtype = flaot)

returns an array of given shape and type, filled with zeros. if the dtype is not provided as an input, the default type for the 
array would be float

In [27]:
# Creating one - dimenional array

In [28]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [29]:
# Creating a 2 dimensional array

In [30]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [31]:
# Creating a one dimensional array of integer type

In [32]:
np.zeros(5, dtype = int)

array([0, 0, 0, 0, 0])

# Ones(shape, dtype = float)

returns an array of given shape and type filled with ones. 

In [33]:
# Creating a one dimensional array

In [35]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [36]:
np.ones(5, dtype = int)

array([1, 1, 1, 1, 1])

# Full(shape, fill_value, dtype = None)

returns an array of given shape and type, fill with fill_value given in input parameters

In [37]:
#Creating a one dimensional array wwith value as 12

In [38]:
    np.full(5,12)

array([12, 12, 12, 12, 12])

In [39]:
# creating a 2 dimensional array with fill value as 9

In [40]:
np.full((2,4),9)

array([[9, 9, 9, 9],
       [9, 9, 9, 9]])

# arange([start,]stop,[step])

returns an array with evenly spaced values within a given interval. if start and step parameter are not given then range start with 0.

In [41]:
# Creating an array with only stop argument

In [42]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [43]:
# Creating an array with start and stop arguments

In [44]:
np.arange(5,12)

array([ 5,  6,  7,  8,  9, 10, 11])

In [45]:
# creating an array with given interval and step value as 0.5

In [46]:
np.arange(3,8,0.5)

array([3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. , 7.5])

# Linespace(start, stop, num=50, endpoint = True)

returns evenly spaced numbers over a specified interval. The number of samples to be returned is specified with the num parameter. the endpoint of the interval can optionally be excluded.

In [47]:
# Creating an evenly spaced array with five numbers within interval 2 to 3

In [48]:
np.linspace(2.0, 3.0, num = 5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [49]:
# creating an array excluding end value

In [50]:
np.linspace(2.0, 3.0, num = 10, endpoint = False)

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

# Random Sampling in NumPy

# rand([d0, d1,.......dn])

it is used to create an array of given shape and populate it with random number from a uniform distribution over [0,1)

it takes only positive arguments.

if no argument is proivde singl float value is returned

In [51]:
# Generating single random number

In [52]:
np.random.rand()

0.8583298730600777

In [53]:
# Generating a one-dimensional array with four random values

In [54]:
np.random.rand(4)

array([0.46253717, 0.06733674, 0.77642649, 0.73177917])

In [55]:
# Generating a two-dimensional array

In [56]:
np.random.rand(2,4)

array([[0.06565772, 0.05413737, 0.03729521, 0.06140483],
       [0.81505667, 0.75699644, 0.08936201, 0.43982339]])

# Randn([d0, d1, ........., dn])

it is used to create an array of given shape and populate it with random samples from a Standard Normal Distributions.

It takes only positive arguments.

it generate an array of shape (d0,d1,...dn) filled with random floats sampled from a univariate normal distributin of mean 0 and variance 1.

In [57]:
# Generating a random sample

In [59]:
np.random.randn()

0.1256447819690873

In [60]:
# Generating a two-dimensional array over N(0, 1)

In [61]:
np.random.randn(2,3)

array([[ 1.70754934,  0.19729667,  0.25837501],
       [-0.06589353,  0.74858993,  0.23723355]])

In [62]:
# Generating a two-dimensional array over N(3, 2.25)

In [63]:
1.5 * np.random.randn(2, 3) + 3

array([[-0.02253821,  1.19317793,  4.50062625],
       [ 2.94954213,  3.99457488,  3.25381432]])

# randint(low, high=None, size=None) 

returns a random integerfrom a discrete uniform distribution with limits of low (inclusive)and high (exclusive). 

If high is None (the default), then results are from 0 to low. 

If the size is specified, it returns an array of the specified size.


In [64]:
# Generating a random integer between 0 and 6

In [65]:
np.random.randint(6)

2

In [66]:
# Generating a random integer between 6 and 9

In [67]:
np.random.randint(6,9)

6

In [69]:
# Generating a one-dimensional array with values between 3 and 9

In [70]:
np.random.randint(3, 9, size=5)

array([5, 8, 5, 4, 7])

In [71]:
# Generating a two-dimensional array with values between 3 and 9

In [72]:
np.random.randint(3, 9, size=(2, 5))

array([[6, 4, 4, 4, 4],
       [7, 3, 4, 3, 3]])

# random(size=None) 
returns a random float value between 0 and 1
which is drawn from the continuous uniform distribution.

In [73]:
# Generating a random float

In [74]:
np.random.random()

0.18403646961200215

In [75]:
# Generating a one-dimensional array

In [76]:
np.random.random(3)

array([0.36949628, 0.36639434, 0.31435777])

In [77]:
# Generating a two-dimensional array

In [78]:
np.random.random((3, 2))

array([[0.38078854, 0.49950409],
       [0.35252601, 0.31766313],
       [0.49449794, 0.83923734]])

# binomial(n, p, size=None) 

returns samples drawn from a binomial distribution with n trials and p probability of success 

where n is greater than 0 and p is in the interval of 0 and 1.

In [79]:
# Number of trials, probability of each trial

In [80]:
n, p = 1, .5

In [81]:
n

1

In [82]:
p

0.5

In [83]:
# Flipping a coin 1 time for 50 times

In [84]:
samples = np.random.binomial(n, p, 50)

In [85]:
samples

array([0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 0])

# normal(mu=0.0, sigma=1.0, size=None) 

draws random samples from a normal (Gaussian) distribution. 

If no arguments provided, a sample will be drawn from N(0, 1).

In [86]:
# Initialize mu and sigma

In [87]:
mu, sigma = 0, 0.1

In [88]:
# Drawing 5 samples in a one-dimensional array

In [89]:
np.random.normal(mu, sigma, 5)

array([-0.00384193,  0.04872532,  0.10061345,  0.05492212, -0.07763597])

In [90]:
# Drawing 10 samples in a two-dimensional array of shape(2,5)

In [92]:
np.random.normal(mu,sigma , (2,5))

array([[ 0.09471777,  0.02023277,  0.15786408, -0.13918716,  0.00147994],
       [ 0.00085172, -0.03596726,  0.02118338,  0.10932999,  0.11555939]])

# uniform(low=0.0, high=1.0, size=None) 

draws samples from a uniform distribution over the interval 0 (including) and 1 (excluding),

if no arguments are provided.

In other words, any value drawn is equally likely within the interval.


In [93]:
# Creating a one-dimensional array with samples drawn within [-1, 0)

In [94]:
np.random.uniform(-1, 0, 10)

array([-0.69166518, -0.78420305, -0.63541296, -0.9039508 , -0.81429181,
       -0.25460778, -0.165036  , -0.6871107 , -0.92253596, -0.60844986])

In [95]:
# Creating a two-dimensional array with samples drawn within [0, 1)

In [96]:
np.random.uniform(size=(5, 2))

array([[0.42433967, 0.39141409],
       [0.08626282, 0.17937663],
       [0.92818758, 0.68660598],
       [0.28790994, 0.75448588],
       [0.75872427, 0.3972708 ]])

# Array Attributes and Methods

# ndim attribute

displays the number of dimensions of an array. 

Using this attribute on n_call_vol and pcr, we expect dimensions to be 1 and 2 respectively. 

In [98]:
# Checking dimensions for n_call_vol array

In [100]:
n_call_vol.ndim

1

In [101]:
n_2d.ndim

2

# shape- 

returns a tuple with the dimensions of the array. 

It may also be used to reshape the array in-place by assigning a tuple of array dimensions to it.

In [102]:
# Checking the shape of the one-dimensional array

In [103]:
n_put_vol.shape

(5,)

In [104]:
# Checking shape of the two-dimensional array

In [106]:
n_2d.shape #It shows 2 rows and 5 columns

(2, 5)

In [107]:
# Printing n_2d with 2 rows and 5 columns

In [108]:
n_2d

array([[52.89, 45.14, 63.84, 77.1 , 74.6 ],
       [49.51, 50.45, 59.11, 80.49, 65.11]])

In [109]:
# Reshaping n_2d using the shape attribute

In [110]:
n_2d.shape = (5, 2)

In [111]:
# Printing reshaped array


In [112]:
n_2d

array([[52.89, 45.14],
       [63.84, 77.1 ],
       [74.6 , 49.51],
       [50.45, 59.11],
       [80.49, 65.11]])

# size -

returns the number of elements in the array.

In [113]:
n_call_vol.size

5

In [114]:
n_2d.size

10

# dtype - 

returns the data-type of the array’s elements. 

NumPy comes with its own data type just like regular built-in data types such as int, float, str, etc.

In [115]:
n_put_vol.dtype

dtype('float64')

In [116]:
# Creating a one-dimensional array with 1000 samples drawn from a normal distribution

In [117]:
samples = np.random.normal(5, 1.5, 1000)

In [118]:
samples

array([5.93981557, 6.62266485, 4.9714569 , 2.39913983, 6.46169518,
       4.11719498, 5.65139704, 3.74162038, 7.19281355, 3.02953253,
       4.6696602 , 5.32780457, 5.2531047 , 6.54464079, 3.43007919,
       4.70523036, 5.6436826 , 5.0318642 , 3.83477327, 3.03206062,
       4.63434465, 7.22523607, 5.85539768, 5.19341311, 5.32246107,
       7.09583785, 3.69241887, 5.52368491, 5.65965566, 6.74814692,
       4.77710839, 4.54246049, 5.14500841, 6.1185663 , 6.83076297,
       5.04228316, 3.57280823, 6.59860081, 5.84874369, 5.32185439,
       2.30184827, 2.59913331, 3.21150671, 2.76181495, 4.24833801,
       5.3538549 , 4.93015483, 5.11237527, 2.35064507, 3.6963147 ,
       4.39206795, 5.90273168, 4.48285962, 4.10449263, 5.17951033,
       4.26402373, 2.68324972, 5.2533202 , 5.86742924, 4.20181632,
       3.87361673, 4.52061225, 6.50430308, 4.88508113, 3.13335312,
       3.60092879, 5.04390133, 3.82871314, 7.31726056, 5.69196119,
       2.80524626, 3.152751  , 4.82430524, 4.74735606, 5.69798

In [120]:
# Creating a two-dimensional array with 25 samples drawn from a normal distribution

In [121]:
samples_2d = np.random.normal(5, 1.5, size=(5, 5))

In [122]:
samples_2d

array([[3.72976422, 5.0313259 , 3.56590859, 4.15442596, 5.82378816],
       [5.25057295, 5.76852545, 0.93164827, 6.91798959, 6.61197358],
       [5.81695803, 2.8479014 , 3.01669612, 5.079474  , 4.36180945],
       [4.52613336, 5.30363246, 6.15363666, 4.27597284, 9.47040976],
       [4.76120558, 3.26829582, 4.02473314, 5.91296293, 3.97225747]])

# mean(a, axis=None) - 

returns the average of the array elements. 

The average is computed over the flattened array by default, otherwise over the specified axis.

# average(a, axis=None) -

returns the average of the array elements and works similar to that of mean().

In [123]:
# Computing mean

In [124]:
np.mean(samples)

4.969254525309065

In [125]:
np.average(samples)

4.969254525309065

In [126]:
# Computing mean with axis=1 (over each row)

In [127]:
np.mean(samples_2d, axis=1)

array([4.46104257, 5.09614197, 4.2245678 , 5.94595702, 4.38789099])

In [128]:
np.average(samples_2d, axis=1)

array([4.46104257, 5.09614197, 4.2245678 , 5.94595702, 4.38789099])

# max(a, axis=None)-

returns the maximum of an array or maximum along an axis.

In [129]:
np.max(samples)

9.428567518137106

In [130]:
np.max(samples_2d, axis=1)

array([5.82378816, 6.91798959, 5.81695803, 9.47040976, 5.91296293])

# median(a, axis=None)-

returns the median along the specified axis.

In [131]:
np.median(samples)

4.949818682382427

In [132]:
np.median(samples_2d)

4.761205577591258

# min(a, axis=None) -

returns the minimum of an array or minimum along an axis.

In [133]:
np.min(samples)

0.2428820649769028

In [134]:
np.min(samples_2d, axis=1)

array([3.56590859, 0.93164827, 2.8479014 , 4.27597284, 3.26829582])

# var(a, axis=None) -

returns the variance of an array or along the specified axis.

In [135]:
np.var(samples)

2.1544427450774575

In [136]:
np.var(samples_2d)

2.61855093756904

In [137]:
# The variance is computed over each column of numbers

In [138]:
np.var(samples_2d, axis=0)

array([0.49153992, 1.35361967, 2.82881378, 1.07962995, 3.84663427])

# std(a, axis=None) -

returns the standard deviation of an array or along the specified axis.

In [139]:
np.std(samples)

1.4678020115388375

In [140]:
np.std(samples)

1.4678020115388375

# sum(a, axis=None) -

returns the sum of array elements.

In [141]:
# Computing sum of all elements within n_put_vol

In [142]:
n_put_vol

array([52.89, 45.14, 63.84, 77.1 , 74.6 ])

In [143]:
np.sum(n_put_vol)

313.57

In [144]:
# Computing sum of all array over each row

In [145]:
samples_2d

array([[3.72976422, 5.0313259 , 3.56590859, 4.15442596, 5.82378816],
       [5.25057295, 5.76852545, 0.93164827, 6.91798959, 6.61197358],
       [5.81695803, 2.8479014 , 3.01669612, 5.079474  , 4.36180945],
       [4.52613336, 5.30363246, 6.15363666, 4.27597284, 9.47040976],
       [4.76120558, 3.26829582, 4.02473314, 5.91296293, 3.97225747]])

In [146]:
np.sum(samples_2d, axis=1)

array([22.30521283, 25.48070983, 21.122839  , 29.72978509, 21.93945494])

# cumsum(a, axis=None) -

returns the cumulative sum of the elements along a given axis

In [147]:
np.cumsum(n_put_vol)

array([ 52.89,  98.03, 161.87, 238.97, 313.57])

In [148]:
# Using np. format to compute the sum

In [149]:
np.sum(samples)

4969.254525309065

In [150]:
# Calling sum() directly on a NumPy object

In [151]:
samples.sum()

4969.254525309065

# Array Manipulation

In [152]:
a = np.array([1, 2, 3])

In [153]:
b = np.array([3, 3, 3])

In [154]:
a * b

array([3, 6, 9])

In [155]:
c= np.array([1, 2, 3])

In [156]:
d = 3

In [157]:
c * d

array([3, 6, 9])

# sqrt(*args) -

returns the positive square-root of an array, elementwise.

In [158]:
# Computing square roots of a given array

In [159]:
np.sqrt([1, 4, 9, 16, 25])

array([1., 2., 3., 4., 5.])

# vstack(tup) -

stacks arrays provided via tup in sequence vertically (row wise).

# hstack(tup) -

stacks arrays provided via tup in sequence horizontally (column wise).

# column_stack(tup) -

stacks 1-dimensional arrays as column into a 2- dimensional array. It takes a sequence of 1-D arrays and stacks them
as columns to make a single 2-D array.

In [160]:
# Creating sample arrays


In [162]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

In [163]:
# Stacking arrays vertically

In [164]:
np.vstack((a, b, c))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [165]:
# Stacking arrays horizontally

In [166]:
np.hstack((a, b, c))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [167]:
# Stacking two arrays together

In [168]:
np.column_stack((a, b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [169]:
# Stacking three arrays together

In [170]:
np.column_stack((a, b, c))

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

# transpose() -

permutes the dimensions of an array.

In [171]:
# Creating a two-dimensional array with shape (2, 4)

In [172]:
a = np.arange(8).reshape(2, 4)

In [173]:
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [174]:
# Transposing the array

In [175]:
a.transpose()

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])